name: Split Packages

on:
  push:
    tags: ['v*']

jobs:
  split:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - local: 'adapters/laravel'
            remote: 'fluxfiles-laravel'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: danharrin/monorepo-split-github-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.SPLIT_TOKEN }}
        with:
          package-directory: ${{ matrix.package.local }}
          split-repository-organization: thai-pc
          split-repository-name: ${{ matrix.package.remote }}
